/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package logins;
import javax.swing.JOptionPane;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import logins.login;
import logins.Room;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class Room extends javax.swing.JFrame {

    /** Creates new form Room */
    public Room() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblRoom = new javax.swing.JTable();
        jTxtroomnumber = new javax.swing.JTextField();
        jTxtcapacity = new javax.swing.JTextField();
        jTxtlocation = new javax.swing.JTextField();
        jTxtcoursecode = new javax.swing.JTextField();
        jTxtlecturerid = new javax.swing.JTextField();
        jBtnRoomnumber = new javax.swing.JButton();
        jBtnCapacity = new javax.swing.JButton();
        jBtnLocation = new javax.swing.JButton();
        jBtnCoursecode = new javax.swing.JButton();
        jBtnLecturerid = new javax.swing.JButton();
        jBtnAdd = new javax.swing.JButton();
        jBtnEdit = new javax.swing.JButton();
        jBtnDelete = new javax.swing.JButton();
        jMessage = new javax.swing.JLabel();
        jBtnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(221, 40, 40));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTblRoom.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "room number", "capacity", "location", "course code", "lecturer id"
            }
        ));
        jScrollPane1.setViewportView(jTblRoom);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 390, 360));
        jPanel1.add(jTxtroomnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 100, -1));
        jPanel1.add(jTxtcapacity, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 100, -1));
        jPanel1.add(jTxtlocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 100, -1));
        jPanel1.add(jTxtcoursecode, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 100, -1));
        jPanel1.add(jTxtlecturerid, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 100, -1));

        jBtnRoomnumber.setText("room number");
        jBtnRoomnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRoomnumberActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnRoomnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jBtnCapacity.setText("capacity");
        jPanel1.add(jBtnCapacity, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 90, -1));

        jBtnLocation.setText("building");
        jPanel1.add(jBtnLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 90, -1));

        jBtnCoursecode.setText("course code");
        jPanel1.add(jBtnCoursecode, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jBtnLecturerid.setText("lecturer id");
        jPanel1.add(jBtnLecturerid, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 90, -1));

        jBtnAdd.setText("ADD");
        jBtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAddActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 60, -1));

        jBtnEdit.setText("EDIT");
        jBtnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEditActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 60, -1));

        jBtnDelete.setText("DELETE");
        jBtnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnDeleteMouseClicked(evt);
            }
        });
        jBtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 80, -1));
        jPanel1.add(jMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 240, 30));

        jBtnBack.setText("BACK");
        jBtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBackActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Downloads\\classroom-management-image.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 470));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnRoomnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRoomnumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnRoomnumberActionPerformed

    private void jBtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAddActionPerformed
    DefaultTableModel model = (DefaultTableModel) jTblRoom.getModel();
    model.addRow(new Object[]{jTxtroomnumber.getText(),jTxtcapacity.getText(),jTxtlocation.getText(),jTxtcoursecode.getText(),jTxtlecturerid.getText()});
    }//GEN-LAST:event_jBtnAddActionPerformed

    private void jBtnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEditActionPerformed
       
       DefaultTableModel model = (DefaultTableModel) jTblRoom.getModel();
        if(jTblRoom.getSelectedRow()==-1){
            if(jTblRoom.getRowCount()==0){
                jMessage.setText("table is empty");
            }else{
                jMessage.setText("you must select an item");
            }
        }else{  
       model.setValueAt(jTxtroomnumber.getText(),jTblRoom.getSelectedRow(),0);
       model.setValueAt(jTxtcapacity.getText(),jTblRoom.getSelectedRow(),1);
       model.setValueAt(jTxtlocation.getText(),jTblRoom.getSelectedRow(),2);
       model.setValueAt(jTxtcoursecode.getText(),jTblRoom.getSelectedRow(),3);
       model.setValueAt(jTxtlecturerid.getText(),jTblRoom.getSelectedRow(),4);
    }//GEN-LAST:event_jBtnEditActionPerformed
    }
    private void jBtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDeleteActionPerformed
         DefaultTableModel model = (DefaultTableModel) jTblRoom.getModel();
         model.removeRow(jTblRoom.getSelectedRow());
         if(jTblRoom.getSelectedRow()==-1){
            if(jTblRoom.getRowCount()==0){
                jMessage.setText("table is empty");
            }else{
                jMessage.setText("you must select an item");
            }
        }else{  
             model.removeRow(jTblRoom.getSelectedRow());
         }
    }//GEN-LAST:event_jBtnDeleteActionPerformed

    private void jBtnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnDeleteMouseClicked
        DefaultTableModel model = (DefaultTableModel) jTblRoom.getModel();
        jTxtroomnumber.setText(model.getValueAt(jTblRoom.getSelectedRow(),0).toString());
        jTxtcapacity.setText(model.getValueAt(jTblRoom.getSelectedRow(),1).toString());
        jTxtlocation.setText(model.getValueAt(jTblRoom.getSelectedRow(),2).toString());
        jTxtcoursecode.setText(model.getValueAt(jTblRoom.getSelectedRow(),3).toString());
        jTxtlecturerid.setText(model.getValueAt(jTblRoom.getSelectedRow(),4).toString());
    }//GEN-LAST:event_jBtnDeleteMouseClicked

    private void jBtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBackActionPerformed
        setVisible(false);
        login info = new login();
        info.setVisible(true);
        
    }//GEN-LAST:event_jBtnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Room().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAdd;
    private javax.swing.JButton jBtnBack;
    private javax.swing.JButton jBtnCapacity;
    private javax.swing.JButton jBtnCoursecode;
    private javax.swing.JButton jBtnDelete;
    private javax.swing.JButton jBtnEdit;
    private javax.swing.JButton jBtnLecturerid;
    private javax.swing.JButton jBtnLocation;
    private javax.swing.JButton jBtnRoomnumber;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jMessage;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTblRoom;
    private javax.swing.JTextField jTxtcapacity;
    private javax.swing.JTextField jTxtcoursecode;
    private javax.swing.JTextField jTxtlecturerid;
    private javax.swing.JTextField jTxtlocation;
    private javax.swing.JTextField jTxtroomnumber;
    // End of variables declaration//GEN-END:variables

}
